# Generated by Django 3.2.9 on 2021-12-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_amigos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigos',
            name='aliass',
            field=models.CharField(default='Aliass*', max_length=255),
        ),
    ]
