# Generated by Django 3.2.9 on 2021-12-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_amigos_aliass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigos',
            name='aliass',
        ),
        migrations.AddField(
            model_name='amigos',
            name='llave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llave_user', to='app1.user'),
        ),
    ]
